name: ci-hourly

on:
  schedule:
    - cron: '30 * * * *' # Run every hour on the half hour
  workflow_dispatch:

jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest
    name: python

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev
      
      - name: Execute feature pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT: ${{ secrets.HOPSWORKS_PROJECT }}
          HOPSWORKS_HOST: ${{ secrets.HOPSWORKS_HOST }}
          ELECTRICITY_MAPS_API_KEY: ${{ secrets.ELECTRICITY_MAPS_API_KEY }}
          ZONES: SE,SE-SE1,SE-SE2,SE-SE3,SE-SE4
        run: uv run python feature_pipeline.py